// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHn-Eio0vVPfzWR6PS1t347Bg23AfNrK0',
    appId: '1:591974579800:web:978bcd62808b3bb5aa542d',
    messagingSenderId: '591974579800',
    projectId: 'travelapp-7f140',
    authDomain: 'travelapp-7f140.firebaseapp.com',
    storageBucket: 'travelapp-7f140.firebasestorage.app',
    measurementId: 'G-H4X0V7GSVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQ41JmsOqlvUTrQtAizNdq8eR_qI1q2M',
    appId: '1:591974579800:android:494b6800de9d8bf3aa542d',
    messagingSenderId: '591974579800',
    projectId: 'travelapp-7f140',
    storageBucket: 'travelapp-7f140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_qoOsFEAH11OIlw0KgXg9hQpgScS3E8',
    appId: '1:591974579800:ios:740c523a037aec5eaa542d',
    messagingSenderId: '591974579800',
    projectId: 'travelapp-7f140',
    storageBucket: 'travelapp-7f140.firebasestorage.app',
    iosBundleId: 'com.tuong.travelai',
  );
}
